version: '1.1.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
clone_depth: 1
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION% ./Saquib.Utils.Naming/Saquib.Utils.Naming.csproj -c Release
test_script:
  - cmd: dotnet test ./Saquib.Utils.Naming.Tests/Saquib.Utils.Naming.Tests.csproj
artifacts:
 - path: '**\*.nupkg'
   name: nuget packages
   type: NuGetPackage
deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: KI7IOyuUwFBgjO/ht34fMYgL92dCASN+T3tPUZj3p8BJKrTVRP91jX0OsDPRliMm
  artifact: nuget packages
